### ISSUE TITLE
would be better if you can correspond old codes and new codes

### ISSUE THREAD

**Issue by tim-lan** [yescallop/areacodes#1]
Great job! but 比如旧的区划代码废止了，如果能列出对应新的代码是哪一个或者哪几个就更好了。这对于比较很多历史统计数据的时间变化会很有意义。

**Comment by yescallop** [comment]
Extremely hard work. These data of code corresponding are very scattered, hence the impossibility of complete accurate corresponding work.

**Comment by mwxmmy** [comment]
java代码，根据区划名称模糊设置查找设置当前最新区划代码，误差较大，勉强使用
`    
List<Areacodes> list = service.list();
        for (Areacodes areacodes : list) {
            if("弃用".equals(areacodes.getStatus())){
                String name = areacodes.getName();
                String province = areacodes.getProvince();
                String s = name.substring(name.length() - 1, name.length());
                if(s.equals("县") || s.equals("市")|| s.equals("区")){
                    name = name.substring(0,name.length()-1);
                }
                String finalName = name;
                List<Areacodes> collect = list.stream()
                        .filter(a -> a.getStatus().equals("启用"))
                        .filter(a -> a.getProvince().equals(province))
                        .filter(a -> a.getName().startsWith(finalName))
                        .limit(1)
                        .collect(Collectors.toList());
                if(collect.size()>0){
                    areacodes.setPid(collect.get(0).getCode());
                    service.saveOrUpdate(areacodes);
                    System.out.println("code"+areacodes.getCode()+"设置pid为"+areacodes.getPid());
                }
            }
        }
`

**Comment by yescallop** [comment]
我刚刚翻新了整个 repo，写了一套用于对应新旧代码的规范。这之后还有许多工作要做，欢迎各位参与其中！
